

from domain.strategies.base import TradingStrategy
from domain.strategies.manager import StrategyManager


class BacktestService:
    def __init__(self, strategy: TradingStrategy, strategy_manager: StrategyManager):
        self.strategy = strategy
        self.strategy_manager = strategy_manager

    def run_backtest(self, historical_data):
        """
        Run a backtest on the provided historical data using the specified strategy.

        :param historical_data: A list of historical price data.
        :return: A list of signals generated by the strategy.
        """
        self.strategy_manager.set_strategy(self.strategy)
        self.strategy_manager.generate_signals(historical_data)
